"""Database updata

Revision ID: 50db156e91c1
Revises: 710fa7b3a096
Create Date: 2024-12-10 23:45:33.627821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50db156e91c1'
down_revision: Union[str, None] = '710fa7b3a096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('salary', sa.Float(), nullable=False))
    op.add_column('vacancy', sa.Column('contacts', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('vacancy', sa.Column('owner', sa.Integer(), nullable=False))
    op.drop_column('vacancy', 'responded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('responded', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_column('vacancy', 'owner')
    op.drop_column('vacancy', 'contacts')
    op.drop_column('vacancy', 'salary')
    # ### end Alembic commands ###
