"""Database create

Revision ID: 710fa7b3a096
Revises: 
Create Date: 2024-12-10 16:29:47.903288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710fa7b3a096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_name', sa.String(length=320), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=320), nullable=False),
    sa.Column('lectures_publication', sa.Boolean(), nullable=False),
    sa.Column('vacancies_publication', sa.Boolean(), nullable=False),
    sa.Column('roles_edit', sa.Boolean(), nullable=False),
    sa.Column('users_block', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('watched_lectures', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('planed_lectures', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('posted_lectures', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('posted_vacancies', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_name', sa.String(length=320), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('responded', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('company', sa.String(length=320), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('lecture')
    # ### end Alembic commands ###
